language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository
#    - extra-google-m2repository
#    - extra-google-google_play_services

branches:
  only:
    - master

notifications:
  email: true

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

install: ./gradlew clean build
script:
- chmod +x ./gradlew
